name: changeset-recover
version: 0.0.0
license: MIT
author: NullVoxPopuli
description: >
  recover utility to generate changeset (https://github.com/changesets/changesets) 
  entries when they'd previously been forgetten. 

  Gives library maintainers a chance to double check merged work without fear of 
  missing attribution in the CHANGELOG. 
repository:
  url: https://github.com/NullVoxPopuli/changeset-recover
  type: https
  directory: .
files:
  - src/**/*
bin: src/bin.js
type: module
engines: {node: ^16.0.0 || >= 18.0.0}
dependencies:
  yargs: ^17.6.2
scripts:
  prepare: pnpm dev:sync
  dev:sync: NODE_OPTIONS='--no-warnings' ts-node --esm ./dev.mts sync-package-json
  lint: eslint . --fix
  format: format -w .
  start: node src/bin.js
devDependencies:
  '@babel/core': ^7.20.12
  '@babel/eslint-parser': ^7.19.1
  '@changesets/changelog-github': ^0.4.8
  '@changesets/cli': ^2.26.0
  '@nullvoxpopuli/eslint-configs': ^3.0.4
  '@pnpm/read-importer-manifest': ^2.0.1
  '@pnpm/write-importer-manifest': ^4.0.0
  '@tsconfig/node-lts-strictest-esm': ^18.12.1
  '@types/node': ^18.11.18
  '@types/yargs': ^17.0.20
  '@typescript-eslint/parser': ^5.49.0
  eslint: ^8.32.0
  prettier: ^2.8.3
  ts-node: ^10.9.1
  typescript: ^4.9.4
volta:
  node: 18.13.0
  pnpm: 7.26.0
